[package]
name = "muchine_learning_tutotial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.126"
serde_derive = "1.0.126"
rusty-machine = "0.5.4"
polars = "0.14.2"
polars-core = {version = "0.14.2", features=["ndarray"]}
smartcore = "0.2.0"