[package]
name = "muchine_learning_tutotial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
read_csv = {path = "./read_csv"}
rusty-machine = "0.5.4"
serde = "1.0.126"
serde_derive = "1.0.126"