[package]
name = "muchine_learning_tutotial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smartcore ="0.2.0"
serde = "1.0.115"
bincode = "1.3.1"
datafusion = "11.0" 
tokio = "1.0" 
csv = "1.2"
ndarray = "0.15.0"
